configs:
  - p/python
  - p/security-audit
  - p/owasp-top-ten

rules:
  - id: ignore-b108-tmp-sqlmap
    patterns:
      - pattern: |
          os.getenv("SQLMAP_OUTPUT_DIR", "/tmp/sqlmap-output")
    message: "B108 is a false positive for default config values"
    languages: [python]
    severity: INFO
    metadata:
      semgrep.ignore: true
