"""Penetration Tester - runs targeted vulnerability checks against the recon surface.

The agent's tools are split across sibling modules in this package so each
file owns one cohesive responsibility:

- ``_decorator`` - ``pentest_tool`` decorator, ``_PentestTool`` Protocol,
  ``_parse_endpoints`` / ``_recon_from_path`` both-shapes adapters.
- ``probes`` - the 25 ``@pentest_tool`` probe wrappers (SQLi, SSRF, XSS,
  XXE, IDOR, JWT, etc.).
- ``cloud`` - the 23 ``@cyber_tool`` cloud / infra wrappers (S3,
  Elasticsearch, Mongo, admin panels, etc.). Dashboards / consul
  / Azure split into port + path / container + SAS-token variants so
  each wrapper carries a single ``scope_filter``.
- ``recon`` - the three typed slicers over ``recon.json``.
- ``findings`` - the ``Save Findings`` workspace writer.

This module imports each wrapper, assembles ``MEMBER.tools``, and re-
exports both the wrappers and their args_schema classes so existing
consumers (tests, ``crew.py``, the contract tests in
``tests/test_pt_args_schemas.py``) keep importing from
``squad.penetration_tester`` directly.
"""

from pathlib import Path

from squad import (
    SquadMember,
    read_attack_plan_tool,
    read_run_file_tool,
    read_run_filelist_tool,
)
from squad.penetration_tester._decorator import (
    _parse_endpoints,
    _PentestFn,
    _PentestTool,
    _recon_from_path,
    pentest_tool,
)
from squad.penetration_tester.cloud import (
    _AdminPanelsArgs,
    _AzureBlobContainerArgs,
    _AzureSasTokenArgs,
    _ConsulVaultPathArgs,
    _ConsulVaultPortArgs,
    _CouchdbCheckArgs,
    _CpanelArgs,
    _DirectadminArgs,
    _ElasticsearchCheckArgs,
    _GrafanaPathArgs,
    _GrafanaPortArgs,
    _KibanaPathArgs,
    _KibanaPortArgs,
    _MongodbCheckArgs,
    _MysqlCheckArgs,
    _PleskArgs,
    _PortainerPathArgs,
    _PortainerPortArgs,
    _PostgresqlCheckArgs,
    _RedisCheckArgs,
    _S3CheckArgs,
    _SensitiveFilesArgs,
    _WebminArgs,
    admin_panels_tool,
    azure_blob_container_check_tool,
    azure_sas_token_check_tool,
    consul_vault_path_check_tool,
    consul_vault_port_check_tool,
    couchdb_tool,
    cpanel_tool,
    directadmin_tool,
    elasticsearch_tool,
    grafana_path_check_tool,
    grafana_port_check_tool,
    kibana_path_check_tool,
    kibana_port_check_tool,
    mongodb_tool,
    mysql_tool,
    plesk_tool,
    portainer_path_check_tool,
    portainer_port_check_tool,
    postgresql_tool,
    redis_tool,
    s3_check_tool,
    sensitive_files_tool,
    webmin_tool,
)
from squad.penetration_tester.findings import _SaveFindingsArgs, save_findings_tool
from squad.penetration_tester.probes import (
    _CmdInjectionArgs,
    _CookieCheckArgs,
    _CorsCheckArgs,
    _CsrfCheckArgs,
    _ErrorDisclosureArgs,
    _HeaderInjectionArgs,
    _HeaderXssArgs,
    _HostHeaderArgs,
    _HppArgs,
    _IdorArgs,
    _JwtCheckArgs,
    _LdapInjectionArgs,
    _NosqliArgs,
    _NucleiScanArgs,
    _OpenRedirectArgs,
    _PathTraversalArgs,
    _PromptInjectionArgs,
    _PrototypePollutionArgs,
    _SourceMapsArgs,
    _SqlmapArgs,
    _SriCheckArgs,
    _SsrfArgs,
    _SstiArgs,
    _XssArgs,
    _XxeArgs,
    cmd_injection_tool,
    cookie_check_tool,
    cors_check_tool,
    csrf_check_tool,
    error_disclosure_tool,
    header_injection_tool,
    header_xss_tool,
    host_header_tool,
    hpp_probe_tool,
    idor_probe_tool,
    jwt_check_tool,
    ldap_injection_tool,
    nosqli_tool,
    nuclei_scan_tool,
    open_redirect_tool,
    path_traversal_tool,
    prompt_injection_tool,
    prototype_pollution_tool,
    source_maps_tool,
    sqlmap_tool,
    sri_check_tool,
    ssrf_probe_tool,
    ssti_probe_tool,
    xss_probe_tool,
    xxe_probe_tool,
)
from squad.penetration_tester.recon import (
    _PtReconEndpointsArgs,
    _PtReconOpenPortsArgs,
    _PtReconSubdomainsArgs,
    recon_endpoints_tool,
    recon_open_ports_tool,
    recon_subdomains_tool,
)

MEMBER = SquadMember(
    dir=Path(__file__).parent,
    tools=[
        # @pentest_tool probes
        nuclei_scan_tool,
        sqlmap_tool,
        cookie_check_tool,
        cors_check_tool,
        csrf_check_tool,
        ssrf_probe_tool,
        header_injection_tool,
        header_xss_tool,
        host_header_tool,
        source_maps_tool,
        ssti_probe_tool,
        hpp_probe_tool,
        open_redirect_tool,
        path_traversal_tool,
        xss_probe_tool,
        sri_check_tool,
        error_disclosure_tool,
        prompt_injection_tool,
        nosqli_tool,
        ldap_injection_tool,
        cmd_injection_tool,
        xxe_probe_tool,
        prototype_pollution_tool,
        idor_probe_tool,
        jwt_check_tool,
        # @cyber_tool cloud / infra
        s3_check_tool,
        azure_blob_container_check_tool,
        azure_sas_token_check_tool,
        elasticsearch_tool,
        couchdb_tool,
        redis_tool,
        mongodb_tool,
        postgresql_tool,
        mysql_tool,
        sensitive_files_tool,
        admin_panels_tool,
        cpanel_tool,
        plesk_tool,
        directadmin_tool,
        webmin_tool,
        grafana_port_check_tool,
        grafana_path_check_tool,
        kibana_port_check_tool,
        kibana_path_check_tool,
        portainer_port_check_tool,
        portainer_path_check_tool,
        consul_vault_port_check_tool,
        consul_vault_path_check_tool,
        # PT recon slicers + Save Findings
        recon_subdomains_tool,
        recon_endpoints_tool,
        recon_open_ports_tool,
        save_findings_tool,
        # Shared workspace wrappers
        read_attack_plan_tool,
        read_run_filelist_tool,
        read_run_file_tool,
    ],
)

__all__ = [
    # Public API
    "MEMBER",
    # Decorator surface (re-exported so test imports stay stable)
    "_PentestFn",
    "_PentestTool",
    "pentest_tool",
    "_parse_endpoints",
    "_recon_from_path",
    # Probe wrappers
    "cmd_injection_tool",
    "cookie_check_tool",
    "cors_check_tool",
    "csrf_check_tool",
    "error_disclosure_tool",
    "header_injection_tool",
    "header_xss_tool",
    "host_header_tool",
    "hpp_probe_tool",
    "idor_probe_tool",
    "jwt_check_tool",
    "ldap_injection_tool",
    "nosqli_tool",
    "nuclei_scan_tool",
    "open_redirect_tool",
    "path_traversal_tool",
    "prompt_injection_tool",
    "prototype_pollution_tool",
    "source_maps_tool",
    "sqlmap_tool",
    "sri_check_tool",
    "ssrf_probe_tool",
    "ssti_probe_tool",
    "xss_probe_tool",
    "xxe_probe_tool",
    # Cloud / infra wrappers
    "admin_panels_tool",
    "azure_blob_container_check_tool",
    "azure_sas_token_check_tool",
    "consul_vault_path_check_tool",
    "consul_vault_port_check_tool",
    "couchdb_tool",
    "cpanel_tool",
    "directadmin_tool",
    "elasticsearch_tool",
    "grafana_path_check_tool",
    "grafana_port_check_tool",
    "kibana_path_check_tool",
    "kibana_port_check_tool",
    "mongodb_tool",
    "mysql_tool",
    "plesk_tool",
    "portainer_path_check_tool",
    "portainer_port_check_tool",
    "postgresql_tool",
    "redis_tool",
    "s3_check_tool",
    "sensitive_files_tool",
    "webmin_tool",
    # Recon slicers + Save Findings
    "recon_endpoints_tool",
    "recon_open_ports_tool",
    "recon_subdomains_tool",
    "save_findings_tool",
    # args_schema classes (per-tool contracts) - re-exported so
    # tests/test_pt_args_schemas.py and any future consumer can keep
    # importing from squad.penetration_tester directly.
    "_AdminPanelsArgs",
    "_AzureBlobContainerArgs",
    "_AzureSasTokenArgs",
    "_CmdInjectionArgs",
    "_ConsulVaultPathArgs",
    "_ConsulVaultPortArgs",
    "_CookieCheckArgs",
    "_CorsCheckArgs",
    "_CouchdbCheckArgs",
    "_CpanelArgs",
    "_CsrfCheckArgs",
    "_DirectadminArgs",
    "_ElasticsearchCheckArgs",
    "_ErrorDisclosureArgs",
    "_GrafanaPathArgs",
    "_GrafanaPortArgs",
    "_HeaderInjectionArgs",
    "_HeaderXssArgs",
    "_HostHeaderArgs",
    "_HppArgs",
    "_IdorArgs",
    "_JwtCheckArgs",
    "_KibanaPathArgs",
    "_KibanaPortArgs",
    "_LdapInjectionArgs",
    "_MongodbCheckArgs",
    "_MysqlCheckArgs",
    "_NosqliArgs",
    "_NucleiScanArgs",
    "_OpenRedirectArgs",
    "_PathTraversalArgs",
    "_PleskArgs",
    "_PortainerPathArgs",
    "_PortainerPortArgs",
    "_PostgresqlCheckArgs",
    "_PromptInjectionArgs",
    "_PrototypePollutionArgs",
    "_PtReconEndpointsArgs",
    "_PtReconOpenPortsArgs",
    "_PtReconSubdomainsArgs",
    "_RedisCheckArgs",
    "_S3CheckArgs",
    "_SaveFindingsArgs",
    "_SensitiveFilesArgs",
    "_SourceMapsArgs",
    "_SqlmapArgs",
    "_SriCheckArgs",
    "_SsrfArgs",
    "_SstiArgs",
    "_WebminArgs",
    "_XssArgs",
    "_XxeArgs",
]
